site_name: Findify
site_favicon: favicon.png
pages:
    - Home: index.md
    - Search API:
        - 'Get started': 'search-api/getstarted.md'
    - Merchant JS:
        - 'Get started': 'merchant-js/getstarted.md'