site_name: Findify
site_favicon: favicon.png
pages:
    - Home: index.md
    - Integrations:
        - 'Shopify': 'integrations/shopify.md'
        - 'Magento': 'integrations/magento.md'
        - 'Custom': 'integrations/custom.md'
    - 'M.JS':
        - 'Get started': 'merchant-js/index.md'
    - Feed:
        - 'Get started': 'feed/index.md'